/**
 * Session memory: append-only transcript + curated memory summary.
 * Invariant #3: Flush before discard — memory.md always written before session context cleared.
 * Invariant #4: Every action logged — every AgentEvent appended to transcript.jsonl.
 */
import { mkdirSync, appendFileSync, existsSync, readFileSync } from 'fs'
import { join } from 'path'
import { homedir } from 'os'
import type { AgentEvent } from '../../shared/types'

const BASE_DIR = join(homedir(), '.octoagent', 'sessions')

function sessionDir(sessionId: string): string {
  const dir = join(BASE_DIR, sessionId)
  mkdirSync(dir, { recursive: true })
  return dir
}

/** Append an event to the session transcript (invariant #4). */
export function appendTranscript(event: AgentEvent): void {
  const dir = sessionDir(event.sessionId)
  const line = JSON.stringify({ ...event, _logged: Date.now() }) + '\n'
  appendFileSync(join(dir, 'transcript.jsonl'), line, 'utf-8')
}

/** Read all events from a session transcript for recovery (invariant #5). */
export function readTranscript(sessionId: string): AgentEvent[] {
  const filePath = join(sessionDir(sessionId), 'transcript.jsonl')
  if (!existsSync(filePath)) return []
  const content = readFileSync(filePath, 'utf-8')
  return content
    .split('\n')
    .filter(Boolean)
    .map((line) => {
      try { return JSON.parse(line) as AgentEvent }
      catch { return null }
    })
    .filter((e): e is AgentEvent => e !== null)
}

/** Get the last N events from a session transcript. */
export function getRecentEvents(sessionId: string, count: number): AgentEvent[] {
  const all = readTranscript(sessionId)
  return all.slice(-count)
}

/** Read the curated memory summary. */
export function readMemory(sessionId: string): string | null {
  const filePath = join(sessionDir(sessionId), 'memory.md')
  if (!existsSync(filePath)) return null
  return readFileSync(filePath, 'utf-8')
}

/**
 * Flush session memory — write memory.md summary.
 * In Phase 5 this will call Claude API for a curated summary.
 * For now it writes a simple event count summary.
 * Invariant #3: Always call flush() before clearing session context.
 */
export async function flush(sessionId: string): Promise<void> {
  const events = readTranscript(sessionId)
  if (events.length === 0) return

  const dir = sessionDir(sessionId)
  const summary = [
    `# Session Memory: ${sessionId}`,
    ``,
    `**Events:** ${events.length}`,
    `**First event:** ${new Date(events[0].timestamp).toISOString()}`,
    `**Last event:** ${new Date(events[events.length - 1].timestamp).toISOString()}`,
    ``,
    `## Event Summary`,
    ...Object.entries(
      events.reduce<Record<string, number>>((acc, e) => {
        acc[e.type] = (acc[e.type] || 0) + 1
        return acc
      }, {})
    ).map(([type, count]) => `- ${type}: ${count}`),
    ``,
    `> Curated summary will be generated by Claude API in Phase 5.`,
    ``,
  ].join('\n')

  const { writeFileSync } = await import('fs')
  writeFileSync(join(dir, 'memory.md'), summary, 'utf-8')
}

/** Get the session directory path. */
export function getSessionDir(sessionId: string): string {
  return sessionDir(sessionId)
}
